apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${NAMESPACE}
  annotations:
    deployer: "${GITLAB_USER_NAME} ${GITLAB_USER_EMAIL}"
    project_url: "${CI_PROJECT_URL}"
    description: "Deployment ${CI_PROJECT_NAME}"
    changelog: "${CI_COMMIT_TITLE}"
    app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
    app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}
  labels:
    ApplicationName: ${KUBE_APPLICATION_NAME}
spec:
  replicas: ${REPLICAS}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ${CI_PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${CI_PROJECT_NAME}
    spec:
      serviceAccountName: ${SERVICE_ACCOUNT_NAME}
      automountServiceAccountToken: true
      containers:
        - name: ${CI_PROJECT_NAME}
          image: ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}
          ports:
            - containerPort: ${APP_PORT}
              protocol: TCP
          envFrom:
            - secretRef:
                name: secret-${CI_PROJECT_NAME}
          livenessProbe:
            httpGet:
              path: /health
              port: ${APP_PORT}
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: ${APP_PORT}
            initialDelaySeconds: 60
            timeoutSeconds: 30
          resources:
            requests:
              memory: ${RESOURCES_REQ_MEM}
              cpu: ${RESOURCES_REQ_CPU}
            limits:
              memory: ${RESOURCES_LIMIT_MEM}
              cpu: ${RESOURCES_LIMIT_CPU}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: topology.kubernetes.io/zone
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
      nodeSelector:
        ${SELECTOR_ROLE}
      imagePullSecrets:
        - name: gitlab-registry-credentials
