apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${NAMESPACE}
  labels:
    ApplicationName: ${KUBE_APPLICATION_NAME}
spec:
  ports:
    - port: ${APP_PORT}
      targetPort: ${APP_PORT}
      protocol: TCP
      name: http
  selector:
    app: ${CI_PROJECT_NAME}
  type: ClusterIP
